#
#  Use this Docker Compose to fetch the latest images from GitHub Container Registry.
#
#  NOTE: These images are built from the latest commit on the main branch and are not 
#  guaranteed to be stable.
#
version: '3.8'
services:
  mongodb:
    container_name: mongodb-praise
    image: mongo:5.0.6
    env_file:
      - .env
    ports:
      - $MONGO_PORT:27017
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - './packages/mongodb/users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro'

  api:
    container_name: api-praise
    image: ghcr.io/givepraise/praise/latest/api:latest
    env_file:
      - .env
    restart: always
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - './packages/api/uploads/:/usr/src/uploads/'      
    links:
      - mongodb

  discord-bot:
    container_name: discord-bot-praise
    image: ghcr.io/givepraise/praise/latest/discord-bot:latest
    env_file:
      - .env
    restart: always
    links:
      - mongodb

  frontend:
    container_name: frontend-praise
    image: ghcr.io/givepraise/praise/latest/frontend:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    links:
      - api

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
