name: Shared
on:
  pull_request:
    paths:
      - 'packages/shared/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace shared build
      - run: yarn workspace shared lint